# -*- coding: utf-8 -*-
"""04- Automate EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EJJK7l5y1iBeq8B2EFyuofBVEW0zcvkD

## Automated EDA Techniques
"""

!pip install ydata_profiling

!pip install pandas_profiling

import pandas_profiling

import seaborn as sns

df=sns.load_dataset('tips')

df.head()

from pandas_profiling import ProfileReport

profile=ProfileReport(df, explorative=True, dark_mode= True)

profile.to_file('output.html')

from ydata_profiling import ProfileReport

profile1=ProfileReport(df, explorative=True, dark_mode= True)

profile1.to_file('output1.html')

profile1

##dtale
!pip install dtale

import pandas as pd
import seaborn as sns

df=sns.load_dataset('titanic')

import dtale.app as dtale_app

dtale_app.USE_NGROK = True

dtale_app.USE_COLAB = True

import dtale
dtale.show(df)

dt

!pip install sweetviz

import sweetviz as sv
report = sv.analyze(df)

report.show_html('newreport.html')

import dtale
import dtale.app as dtale_app
dtale_app.USE_COLAB = True

dtale.show(df)

!pip install dataprep

from dataprep.eda import create_report

import pandas as pd
import seaborn as sns

df=sns.load_dataset('titanic')

create_report(df).save('sataprep.html')

!pip install lux

import lux
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/college.csv")
df

from google.colab import output
output.enable_custom_widget_manager()

from google.colab import output
output.disable_custom_widget_manager()

from google.colab import output
output.enable_custom_widget_manager()

from google.colab import output
output.disable_custom_widget_manager()

from google.colab import output
output.enable_custom_widget_manager()

from google.colab import output
output.disable_custom_widget_manager()

! pip install lux-api
! jupyter nbextension install --py luxwidget
! jupyter nbextension enable --py luxwidget

import lux
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/college.csv")
df

!pip install pandas-visual-analysis

from pandas_visual_analysis import VisualAnalysis
VisualAnalysis(df)

from google.colab import output
output.enable_custom_widget_manager()

from google.colab import output
output.disable_custom_widget_manager()

from google.colab import output
output.enable_custom_widget_manager()

from google.colab import output
output.disable_custom_widget_manager()

!pip install pandas_visual_analysis

from pandas_visual_analysis import VisualAnalysis
VisualAnalysis(df)



























